name: Rust

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: jetli/wasm-pack-action@v0.3.0
      - uses: actions/checkout@v2
      - run: |
          (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
          (test -x $HOME/.cargo/bin/cargo-generate || cargo install --vers "^0.2" cargo-generate)
          cargo install-update -a
          cargo generate --git . --name testing
          mv Cargo.toml Cargo.toml.tmpl
          cd testing
          wasm-pack build
          wasm-pack test --chrome --firefox --headless
